<Project>

  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageVersion Include="Spectre.Console" Version="0.57.2" />
    <PackageVersion Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageVersion Include="Spectre.Console.Testing" Version="0.57.2" />
    <PackageVersion Include="YamlDotNet" Version="18.1.0" />
    <PackageVersion Include="CycloneDX.Core" Version="12.1.2" />
    <PackageVersion Include="TUnit" Version="1.67.0" />
    <PackageVersion Include="MinVer" Version="8.0.0" />
  </ItemGroup>

</Project>
