<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Spectre.Console.Testing" />
    <PackageReference Include="TUnit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Attributary.Cli\Attributary.Cli.csproj" />
  </ItemGroup>

</Project>
