<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Attributary.Domain\Attributary.Domain.csproj" />
    <ProjectReference Include="..\Attributary.Diagnostics\Attributary.Diagnostics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="SpdxLicenseData\spdx-subset.json" />
  </ItemGroup>

</Project>
