<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Attributary.Domain\Attributary.Domain.csproj" />
    <ProjectReference Include="..\Attributary.Diagnostics\Attributary.Diagnostics.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="YamlDotNet" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="DefaultRules.yaml" />
  </ItemGroup>

</Project>
